packages:
  - '.'
  - 'tests'
  - 'example'

trustPolicy: no-downgrade
blockExoticSubdeps: true

allowBuilds:
  puppeteer: true
  simple-git-hooks: false

minimumReleaseAge: 10080

minimumReleaseAgeExclude:
  - '@rsbuild/*'
  - '@rslib/*'
  - '@rslint/*'
  - '@rspack/*'
  - '@rspress/*'
  - '@rstackjs/*'
  - '@rstest/*'
  - '@typescript/*'
  - 'rsbuild-plugin-*'
  - rstack
  - typescript
