packages:
  - '.'
  - 'tests'
  - 'example'

allowBuilds:
  puppeteer: true
  simple-git-hooks: false

minimumReleaseAgeExclude:
  - '@rspack/*'
  - '@rsbuild/*'
  - '@rslib/*'
  - '@rstest/*'
  - '@rslint/*'
  - '@typescript/*'
  - typescript
